Modify PowerPoint GitHub examples repository for document processing playground
SyncfusionExamples/PowerPoint-Examples pull request #77
Opened 2024-09-09 16:26 UTC by DharanitharanA

**Description:**
Changed below GitHub examples for play ground button
1. Security
2. SmartArt
3. Macros
4. PowerPoint presentation
5. Slides
6. Shapes
7. Tables
8. Sections

2024-09-10 15:57 UTC, LokeshBaskar requested changes
Please address the feedbacks

2024-09-10 15:57 UTC, LokeshBaskar commented on Macros/Load-and-save-macro-PowerPoint/.NET/Load-and-save-macro-PowerPoint/Load-and-save-macro-PowerPoint.csproj
Please remove the macro file changes it is already changes done.

2024-09-10 15:57 UTC, LokeshBaskar commented on Shapes/Create-PowerPoint-groupshape/.NET/Create-PowerPoint-groupshape/Program.cs
> +using FileStream pictureStream = new FileStream(@"Data/Image.jpg", FileMode.Open);
Please use the Path.GetFullPath

2024-09-10 16:08 UTC, DharanitharanA commented on Shapes/Create-PowerPoint-groupshape/.NET/Create-PowerPoint-groupshape/Program.cs
> +using FileStream pictureStream = new FileStream(@"Data/Image.jpg", FileMode.Open);
Added properly

2024-09-10 16:08 UTC, DharanitharanA commented on Macros/Load-and-save-macro-PowerPoint/.NET/Load-and-save-macro-PowerPoint/Load-and-save-macro-PowerPoint.csproj
Removed the changes

2024-09-10 16:11 UTC, LokeshBaskar approved these changes
No concerns

2024-09-11 05:24 UTC, MohanaselvamJothi approved these changes

2024-09-11 05:24 UTC, merged